// <auto-generated />
using System;
using JobPortal.AppDbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JobPortal.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230515131432_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("JobPortal.Models.AllJobsClasses", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("JobClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("JobClassId");

                    b.HasIndex("JobId");

                    b.ToTable("AllJobsClasses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e2865ba0-ee6c-43d8-a61e-4b9df0f1d386"),
                            IsDeleted = false,
                            JobClassId = new Guid("642a9e91-5c4a-4284-aa0f-69e39a93ea6d"),
                            JobId = new Guid("a8c485f2-b08b-45bb-b1cf-8fd43556e00e")
                        },
                        new
                        {
                            Id = new Guid("0d84a83a-3460-41e1-a942-49dd6d0411bd"),
                            IsDeleted = false,
                            JobClassId = new Guid("63acd142-d323-42c5-a453-1b67f40fd073"),
                            JobId = new Guid("a8c485f2-b08b-45bb-b1cf-8fd43556e00e")
                        },
                        new
                        {
                            Id = new Guid("02d42141-3627-48e2-a9ee-4142f85ca4e5"),
                            IsDeleted = false,
                            JobClassId = new Guid("930c379d-d9e6-4a48-82b0-4f586d6aafc8"),
                            JobId = new Guid("a8c485f2-b08b-45bb-b1cf-8fd43556e00e")
                        },
                        new
                        {
                            Id = new Guid("63c2a7a6-8ebb-4bc9-ac98-8465abbb9994"),
                            IsDeleted = false,
                            JobClassId = new Guid("642a9e91-5c4a-4284-aa0f-69e39a93ea6d"),
                            JobId = new Guid("eec67987-eb6a-4251-95aa-ede40e76332f")
                        },
                        new
                        {
                            Id = new Guid("a4b97db1-2aff-49a7-be60-c59867fd74d7"),
                            IsDeleted = false,
                            JobClassId = new Guid("63acd142-d323-42c5-a453-1b67f40fd073"),
                            JobId = new Guid("eec67987-eb6a-4251-95aa-ede40e76332f")
                        },
                        new
                        {
                            Id = new Guid("6c931ccd-e4db-4671-a7b9-b5be4b1b69ca"),
                            IsDeleted = false,
                            JobClassId = new Guid("930c379d-d9e6-4a48-82b0-4f586d6aafc8"),
                            JobId = new Guid("4db3c416-6eae-4f01-bfd3-1ff3b45aea98")
                        });
                });

            modelBuilder.Entity("JobPortal.Models.AppliedJobs", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("JobsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.HasIndex("JobsId");

                    b.ToTable("AppliedJobs");
                });

            modelBuilder.Entity("JobPortal.Models.Candidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AboutMe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("CurrentCompany")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExpectedSalary")
                        .HasColumnType("int");

                    b.Property<string>("Experience")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExperienceTime")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Location")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Phone")
                        .HasColumnType("float");

                    b.Property<string>("ProfileImg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Qualification")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Candidate");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1163535c-d87f-4a75-8e85-e0d69eb9f0ea"),
                            AboutMe = "Are you a User Experience Designer with a track record of delivering intuitive digital experiences that drive results? Are you a strategic storyteller and systems thinker who can concept and craft smart, world-class campaigns across a variety of mediums?\r\n\r\nDeloitte's Green Dot Agency is looking to add a Lead User Experience Designer to our experience design team. We want a passionate creative who's inspired by new trends and emerging technologies, and is able to integrate them into memorable user experiences. A problem solver who is entrepreneurial, collaborative, hungry, and humble; can deliver beautifully designed, leading-edge experiences under tight deadlines;",
                            Age = 23,
                            CurrentCompany = "Fresh Graduate",
                            ExpectedSalary = 300,
                            Experience = ".Net Developer",
                            ExperienceTime = 5,
                            IsDeleted = false,
                            Location = 0,
                            Name = "Hammad Mirza",
                            Phone = 3000000.0,
                            ProfileImg = "https://th.bing.com/th/id/R.219c36f0da053be6810bf890683de60a?rik=TMTQOLdr87KvBA&pid=ImgRaw&r=0",
                            Qualification = 0,
                            UserId = "995ce588-b342-47b8-88f7-349365f898f9"
                        },
                        new
                        {
                            Id = new Guid("31bb5001-4266-4b90-992e-2a729b26d26b"),
                            AboutMe = "Are you a User Experience Designer with a track record of delivering intuitive digital experiences that drive results? Are you a strategic storyteller and systems thinker who can concept and craft smart, world-class campaigns across a variety of mediums?\r\n\r\nDeloitte's Green Dot Agency is looking to add a Lead User Experience Designer to our experience design team. We want a passionate creative who's inspired by new trends and emerging technologies, and is able to integrate them into memorable user experiences. A problem solver who is entrepreneurial, collaborative, hungry, and humble; can deliver beautifully designed, leading-edge experiences under tight deadlines;",
                            Age = 23,
                            CurrentCompany = "Fresh Graduate",
                            ExpectedSalary = 400,
                            Experience = "Php Laravel",
                            ExperienceTime = 6,
                            IsDeleted = false,
                            Location = 0,
                            Name = "Ahtesham",
                            Phone = 3000000.0,
                            ProfileImg = "https://th.bing.com/th/id/R.219c36f0da053be6810bf890683de60a?rik=TMTQOLdr87KvBA&pid=ImgRaw&r=0",
                            Qualification = 0,
                            UserId = "cc53dc1c-a0d0-49a3-8f31-06b320fe22a9"
                        },
                        new
                        {
                            Id = new Guid("6209c878-b598-4939-bccf-909e58d12504"),
                            AboutMe = "Are you a User Experience Designer with a track record of delivering intuitive digital experiences that drive results? Are you a strategic storyteller and systems thinker who can concept and craft smart, world-class campaigns across a variety of mediums?\r\n\r\nDeloitte's Green Dot Agency is looking to add a Lead User Experience Designer to our experience design team. We want a passionate creative who's inspired by new trends and emerging technologies, and is able to integrate them into memorable user experiences. A problem solver who is entrepreneurial, collaborative, hungry, and humble; can deliver beautifully designed, leading-edge experiences under tight deadlines;",
                            Age = 23,
                            CurrentCompany = "Fresh Graduate",
                            ExpectedSalary = 500,
                            Experience = "React Designer",
                            ExperienceTime = 8,
                            IsDeleted = false,
                            Location = 1,
                            Name = "Sohaib",
                            Phone = 3000000.0,
                            ProfileImg = "https://th.bing.com/th/id/R.219c36f0da053be6810bf890683de60a?rik=TMTQOLdr87KvBA&pid=ImgRaw&r=0",
                            Qualification = 1,
                            UserId = "4e9e311a-0926-423c-b136-eab5ba39998a"
                        });
                });

            modelBuilder.Entity("JobPortal.Models.CandidateSkills", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.HasIndex("SkillId");

                    b.ToTable("CandidateSkills");

                    b.HasData(
                        new
                        {
                            Id = new Guid("66b6ad12-bce1-4928-a59d-de02192a7c10"),
                            CandidateId = new Guid("1163535c-d87f-4a75-8e85-e0d69eb9f0ea"),
                            IsDeleted = false,
                            SkillId = new Guid("9a126650-2936-442e-92ba-7d7dc32ff6f9")
                        },
                        new
                        {
                            Id = new Guid("4cf506e5-818e-4f35-ac3c-000f3e87a604"),
                            CandidateId = new Guid("1163535c-d87f-4a75-8e85-e0d69eb9f0ea"),
                            IsDeleted = false,
                            SkillId = new Guid("010039fb-a687-4db5-8ada-3b586d3a4788")
                        },
                        new
                        {
                            Id = new Guid("af2e3fb6-a3b7-4e1a-83e4-5ee05dde72d7"),
                            CandidateId = new Guid("1163535c-d87f-4a75-8e85-e0d69eb9f0ea"),
                            IsDeleted = false,
                            SkillId = new Guid("b749f4b8-3bc3-4a05-816b-56e0d12dfaaa")
                        },
                        new
                        {
                            Id = new Guid("232c30ea-e8f6-446a-9af1-a2a20cc1c422"),
                            CandidateId = new Guid("31bb5001-4266-4b90-992e-2a729b26d26b"),
                            IsDeleted = false,
                            SkillId = new Guid("aafbde46-32ee-45bd-b52a-a76a1ac12a78")
                        },
                        new
                        {
                            Id = new Guid("26ae6b7d-0ac2-461a-9a11-42f965a2d977"),
                            CandidateId = new Guid("6209c878-b598-4939-bccf-909e58d12504"),
                            IsDeleted = false,
                            SkillId = new Guid("0b886a97-0b5a-44e0-b1a9-c1ddecb67f2d")
                        },
                        new
                        {
                            Id = new Guid("2aa2ed81-38c6-47a3-bfd0-90c031f340df"),
                            CandidateId = new Guid("6209c878-b598-4939-bccf-909e58d12504"),
                            IsDeleted = false,
                            SkillId = new Guid("83c89321-daf9-4ade-b229-d57615a32f10")
                        },
                        new
                        {
                            Id = new Guid("037bb42e-67a5-4105-bb3c-539bb8d8a906"),
                            CandidateId = new Guid("6209c878-b598-4939-bccf-909e58d12504"),
                            IsDeleted = false,
                            SkillId = new Guid("2dd27837-b570-4c81-8bfc-bf8cad8323b6")
                        });
                });

            modelBuilder.Entity("JobPortal.Models.Employer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompanyAbout")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyLogo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CompanySize")
                        .HasColumnType("int");

                    b.Property<string>("CompanyWebsite")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Founded")
                        .HasColumnType("datetime2");

                    b.Property<string>("Headquarters")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employer");

                    b.HasData(
                        new
                        {
                            Id = new Guid("262ff2ba-d323-4916-b767-e9f1707ef7a2"),
                            CompanyAbout = "Are you a User Experience Designer with a track record of delivering intuitive digital experiences that drive results? Are you a strategic storyteller and systems thinker who can concept and craft smart, world-class campaigns across a variety of mediums?\r\n\r\nDeloitte's Green Dot Agency is looking to add a Lead User Experience Designer to our experience design team. We want a passionate creative who's inspired by new trends and emerging technologies, and is able to integrate them into memorable user experiences. A problem solver who is entrepreneurial, collaborative, hungry, and humble; can deliver beautifully designed, leading-edge experiences under tight deadlines; and who has demonstrated proven expertise.",
                            CompanyLogo = "https://th.bing.com/th/id/R.219c36f0da053be6810bf890683de60a?rik=TMTQOLdr87KvBA&pid=ImgRaw&r=0",
                            CompanyName = "Avitex Agency",
                            CompanySize = 200,
                            CompanyWebsite = "https://jobs.nokriwp.com/",
                            Founded = new DateTime(2023, 5, 15, 13, 14, 32, 139, DateTimeKind.Utc).AddTicks(3264),
                            Headquarters = "Las Vegas, NV 89107, USA",
                            Industry = "It",
                            IsDeleted = false,
                            UserId = "2fe7daaa-bb2f-43a6-915b-083816e43b87"
                        },
                        new
                        {
                            Id = new Guid("680b65c6-46cf-48ac-88f7-29ab807b29d5"),
                            CompanyAbout = "Are you a User Experience Designer with a track record of delivering intuitive digital experiences that drive results? Are you a strategic storyteller and systems thinker who can concept and craft smart, world-class campaigns across a variety of mediums?\r\n\r\nDeloitte's Green Dot Agency is looking to add a Lead User Experience Designer to our experience design team. We want a passionate creative who's inspired by new trends and emerging technologies, and is able to integrate them into memorable user experiences. A problem solver who is entrepreneurial, collaborative, hungry, and humble; can deliver beautifully designed, leading-edge experiences under tight deadlines; and who has demonstrated proven expertise.",
                            CompanyLogo = "https://th.bing.com/th/id/R.219c36f0da053be6810bf890683de60a?rik=TMTQOLdr87KvBA&pid=ImgRaw&r=0",
                            CompanyName = "Demo 1",
                            CompanySize = 50,
                            CompanyWebsite = "https://jobs.nokriwp.com/",
                            Founded = new DateTime(2023, 5, 15, 13, 14, 32, 139, DateTimeKind.Utc).AddTicks(3269),
                            Headquarters = "Lahore",
                            Industry = "It",
                            IsDeleted = false,
                            UserId = "088fffd7-94b4-448e-9b67-5619fcf19441"
                        },
                        new
                        {
                            Id = new Guid("4ea1f880-57ef-4f0b-8a19-5aa356e93091"),
                            CompanyAbout = "Are you a User Experience Designer with a track record of delivering intuitive digital experiences that drive results? Are you a strategic storyteller and systems thinker who can concept and craft smart, world-class campaigns across a variety of mediums?\r\n\r\nDeloitte's Green Dot Agency is looking to add a Lead User Experience Designer to our experience design team. We want a passionate creative who's inspired by new trends and emerging technologies, and is able to integrate them into memorable user experiences. A problem solver who is entrepreneurial, collaborative, hungry, and humble; can deliver beautifully designed, leading-edge experiences under tight deadlines; and who has demonstrated proven expertise.",
                            CompanyLogo = "https://th.bing.com/th/id/R.219c36f0da053be6810bf890683de60a?rik=TMTQOLdr87KvBA&pid=ImgRaw&r=0",
                            CompanyName = "Honda",
                            CompanySize = 600,
                            CompanyWebsite = "https://jobs.nokriwp.com/",
                            Founded = new DateTime(2023, 5, 15, 13, 14, 32, 139, DateTimeKind.Utc).AddTicks(3274),
                            Headquarters = "Islamabad",
                            Industry = "Machenical",
                            IsDeleted = false,
                            UserId = "06e4bc68-0d75-429c-b513-e12c2ab03494"
                        });
                });

            modelBuilder.Entity("JobPortal.Models.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DeadLine")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EmployerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("EndBudget")
                        .HasColumnType("float");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("JobExperience")
                        .HasColumnType("int");

                    b.Property<DateTime>("JobPosted")
                        .HasColumnType("datetime2");

                    b.Property<int>("JobShift")
                        .HasColumnType("int");

                    b.Property<int>("JobStatus")
                        .HasColumnType("int");

                    b.Property<int>("Location")
                        .HasColumnType("int");

                    b.Property<int>("Qualifications")
                        .HasColumnType("int");

                    b.Property<string>("Responsibility")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SalaryType")
                        .HasColumnType("int");

                    b.Property<double>("StartBudget")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("Vacancy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployerId");

                    b.ToTable("Jobs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a8c485f2-b08b-45bb-b1cf-8fd43556e00e"),
                            DeadLine = new DateTime(2023, 5, 20, 18, 14, 32, 63, DateTimeKind.Local).AddTicks(3479),
                            Description = "Dolor justo tempor duo ipsum accusam rebum gubergren erat. Elitr stet dolor vero clita labore gubergren. Kasd sed ipsum elitr clita rebum ut sea diam tempor. Sadipscing nonumy vero labore invidunt dolor sed, eirmod dolore amet aliquyam consetetur lorem, amet elitr clita et sed consetetur dolore accusam. Vero kasd nonumy justo rebum stet. Ipsum amet sed lorem sea magna. Rebum vero dolores dolores elitr vero dolores magna, stet sea sadipscing stet et. Est voluptua et sanctus at sanctus erat vero sed sed, amet duo no diam clita rebum duo, accusam tempor takimata clita stet nonumy rebum est invidunt stet, dolor.",
                            EmployerId = new Guid("262ff2ba-d323-4916-b767-e9f1707ef7a2"),
                            EndBudget = 456.0,
                            Icon = "https://img.freepik.com/premium-vector/gradient-business-investment-logo-design_269830-887.jpg?w=2000",
                            IsDeleted = false,
                            JobExperience = 1,
                            JobPosted = new DateTime(2023, 5, 15, 18, 14, 32, 63, DateTimeKind.Local).AddTicks(3567),
                            JobShift = 0,
                            JobStatus = 0,
                            Location = 0,
                            Qualifications = 0,
                            Responsibility = "Magna et elitr diam sed lorem. Diam diam stet erat no est est. Accusam sed lorem stet voluptua sit sit at stet consetetur, takimata at diam kasd gubergren elitr dolor",
                            SalaryType = 0,
                            StartBudget = 123.0,
                            Title = "Marketing Manager",
                            Type = 0,
                            Vacancy = 20
                        },
                        new
                        {
                            Id = new Guid("eec67987-eb6a-4251-95aa-ede40e76332f"),
                            DeadLine = new DateTime(2023, 5, 20, 18, 14, 32, 63, DateTimeKind.Local).AddTicks(3479),
                            Description = "Dolor justo tempor duo ipsum accusam rebum gubergren erat. Elitr stet dolor vero clita labore gubergren. Kasd sed ipsum elitr clita rebum ut sea diam tempor. Sadipscing nonumy vero labore invidunt dolor sed, eirmod dolore amet aliquyam consetetur lorem, amet elitr clita et sed consetetur dolore accusam. Vero kasd nonumy justo rebum stet. Ipsum amet sed lorem sea magna. Rebum vero dolores dolores elitr vero dolores magna, stet sea sadipscing stet et. Est voluptua et sanctus at sanctus erat vero sed sed, amet duo no diam clita rebum duo, accusam tempor takimata clita stet nonumy rebum est invidunt stet, dolor.",
                            EmployerId = new Guid("680b65c6-46cf-48ac-88f7-29ab807b29d5"),
                            EndBudget = 777.0,
                            Icon = "https://media.istockphoto.com/id/1304359165/vector/motion-data-speed-g-letter-logo-design.jpg?s=612x612&w=0&k=20&c=2A0yYWv8zHhztdShuGoVW87yJZqseV6AKJX0QL2cVuQ=",
                            IsDeleted = false,
                            JobExperience = 6,
                            JobPosted = new DateTime(2023, 5, 15, 18, 14, 32, 63, DateTimeKind.Local).AddTicks(3590),
                            JobShift = 0,
                            JobStatus = 0,
                            Location = 2,
                            Qualifications = 0,
                            Responsibility = "Magna et elitr diam sed lorem. Diam diam stet erat no est est. Accusam sed lorem stet voluptua sit sit at stet consetetur, takimata at diam kasd gubergren elitr dolor",
                            SalaryType = 0,
                            StartBudget = 334.0,
                            Title = "Software Engineer",
                            Type = 0,
                            Vacancy = 5
                        },
                        new
                        {
                            Id = new Guid("4db3c416-6eae-4f01-bfd3-1ff3b45aea98"),
                            DeadLine = new DateTime(2023, 5, 20, 18, 14, 32, 63, DateTimeKind.Local).AddTicks(3479),
                            Description = "Dolor justo tempor duo ipsum accusam rebum gubergren erat. Elitr stet dolor vero clita labore gubergren. Kasd sed ipsum elitr clita rebum ut sea diam tempor. Sadipscing nonumy vero labore invidunt dolor sed, eirmod dolore amet aliquyam consetetur lorem, amet elitr clita et sed consetetur dolore accusam. Vero kasd nonumy justo rebum stet. Ipsum amet sed lorem sea magna. Rebum vero dolores dolores elitr vero dolores magna, stet sea sadipscing stet et. Est voluptua et sanctus at sanctus erat vero sed sed, amet duo no diam clita rebum duo, accusam tempor takimata clita stet nonumy rebum est invidunt stet, dolor.",
                            EmployerId = new Guid("4ea1f880-57ef-4f0b-8a19-5aa356e93091"),
                            EndBudget = 340.0,
                            Icon = "https://www.logodesign.net/images/abstract-logo.png",
                            IsDeleted = false,
                            JobExperience = 3,
                            JobPosted = new DateTime(2023, 5, 15, 18, 14, 32, 63, DateTimeKind.Local).AddTicks(3597),
                            JobShift = 2,
                            JobStatus = 0,
                            Location = 0,
                            Qualifications = 1,
                            Responsibility = "Magna et elitr diam sed lorem. Diam diam stet erat no est est. Accusam sed lorem stet voluptua sit sit at stet consetetur, takimata at diam kasd gubergren elitr dolor",
                            SalaryType = 0,
                            StartBudget = 190.0,
                            Title = "Product Designer",
                            Type = 5,
                            Vacancy = 50
                        });
                });

            modelBuilder.Entity("JobPortal.Models.JobClass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("name")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("JobClass");

                    b.HasData(
                        new
                        {
                            Id = new Guid("642a9e91-5c4a-4284-aa0f-69e39a93ea6d"),
                            IsDeleted = false,
                            name = 0
                        },
                        new
                        {
                            Id = new Guid("63acd142-d323-42c5-a453-1b67f40fd073"),
                            IsDeleted = false,
                            name = 1
                        },
                        new
                        {
                            Id = new Guid("930c379d-d9e6-4a48-82b0-4f586d6aafc8"),
                            IsDeleted = false,
                            name = 2
                        });
                });

            modelBuilder.Entity("JobPortal.Models.JobSkills", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("SkillId");

                    b.ToTable("JobSkills");

                    b.HasData(
                        new
                        {
                            Id = new Guid("037bb42e-67a5-4105-bb3c-539bb8d8a906"),
                            IsDeleted = false,
                            JobId = new Guid("a8c485f2-b08b-45bb-b1cf-8fd43556e00e"),
                            SkillId = new Guid("aafbde46-32ee-45bd-b52a-a76a1ac12a78")
                        },
                        new
                        {
                            Id = new Guid("fad6993c-c654-4c17-9078-174818d7236f"),
                            IsDeleted = false,
                            JobId = new Guid("a8c485f2-b08b-45bb-b1cf-8fd43556e00e"),
                            SkillId = new Guid("bae33518-8dc8-4d53-80ca-e8f58a9fd808")
                        },
                        new
                        {
                            Id = new Guid("272eaf21-8b37-4562-b440-96b4befe752f"),
                            IsDeleted = false,
                            JobId = new Guid("a8c485f2-b08b-45bb-b1cf-8fd43556e00e"),
                            SkillId = new Guid("0b886a97-0b5a-44e0-b1a9-c1ddecb67f2d")
                        },
                        new
                        {
                            Id = new Guid("ca58283f-d5f4-4eb0-92e3-6873e6821129"),
                            IsDeleted = false,
                            JobId = new Guid("eec67987-eb6a-4251-95aa-ede40e76332f"),
                            SkillId = new Guid("0b886a97-0b5a-44e0-b1a9-c1ddecb67f2d")
                        },
                        new
                        {
                            Id = new Guid("340a0320-8302-4860-999f-3a256a785a20"),
                            IsDeleted = false,
                            JobId = new Guid("eec67987-eb6a-4251-95aa-ede40e76332f"),
                            SkillId = new Guid("010039fb-a687-4db5-8ada-3b586d3a4788")
                        },
                        new
                        {
                            Id = new Guid("f0f7f73e-aad5-416a-af2f-0153f313ae05"),
                            IsDeleted = false,
                            JobId = new Guid("4db3c416-6eae-4f01-bfd3-1ff3b45aea98"),
                            SkillId = new Guid("010039fb-a687-4db5-8ada-3b586d3a4788")
                        });
                });

            modelBuilder.Entity("JobPortal.Models.Skills", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("JobSkill")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aafbde46-32ee-45bd-b52a-a76a1ac12a78"),
                            IsDeleted = false,
                            JobSkill = "Php"
                        },
                        new
                        {
                            Id = new Guid("bae33518-8dc8-4d53-80ca-e8f58a9fd808"),
                            IsDeleted = false,
                            JobSkill = "JS"
                        },
                        new
                        {
                            Id = new Guid("0b886a97-0b5a-44e0-b1a9-c1ddecb67f2d"),
                            IsDeleted = false,
                            JobSkill = "Designing"
                        },
                        new
                        {
                            Id = new Guid("9a126650-2936-442e-92ba-7d7dc32ff6f9"),
                            IsDeleted = false,
                            JobSkill = "React Native"
                        },
                        new
                        {
                            Id = new Guid("83c89321-daf9-4ade-b229-d57615a32f10"),
                            IsDeleted = false,
                            JobSkill = "Arts"
                        },
                        new
                        {
                            Id = new Guid("010039fb-a687-4db5-8ada-3b586d3a4788"),
                            IsDeleted = false,
                            JobSkill = ".Net"
                        },
                        new
                        {
                            Id = new Guid("2dd27837-b570-4c81-8bfc-bf8cad8323b6"),
                            IsDeleted = false,
                            JobSkill = "Java"
                        },
                        new
                        {
                            Id = new Guid("e4599076-fa12-4fe9-a8e4-35130d73729e"),
                            IsDeleted = false,
                            JobSkill = "MERN Stack"
                        },
                        new
                        {
                            Id = new Guid("b749f4b8-3bc3-4a05-816b-56e0d12dfaaa"),
                            IsDeleted = false,
                            JobSkill = "Architecture"
                        },
                        new
                        {
                            Id = new Guid("f235f414-fc41-4acb-a1ee-1fd79aea7eae"),
                            IsDeleted = false,
                            JobSkill = "Management"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1d8bbcb9-6d72-4776-b97a-54dd330775ca",
                            ConcurrencyStamp = "7151b06b-6891-42af-91ee-f7c4de9c62d9",
                            Name = "admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "7023e28f-c1dc-42cd-ad76-858802f45979",
                            ConcurrencyStamp = "5cd972a9-e093-49ce-9297-c7908857a981",
                            Name = "candidate",
                            NormalizedName = "CANDIDATE"
                        },
                        new
                        {
                            Id = "b189a208-8a38-42c5-9922-5dcb918e85c9",
                            ConcurrencyStamp = "742a4575-753d-47f2-a376-17982fc4925c",
                            Name = "employer",
                            NormalizedName = "EMPLOYER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "2fe7daaa-bb2f-43a6-915b-083816e43b87",
                            RoleId = "b189a208-8a38-42c5-9922-5dcb918e85c9"
                        },
                        new
                        {
                            UserId = "088fffd7-94b4-448e-9b67-5619fcf19441",
                            RoleId = "b189a208-8a38-42c5-9922-5dcb918e85c9"
                        },
                        new
                        {
                            UserId = "06e4bc68-0d75-429c-b513-e12c2ab03494",
                            RoleId = "b189a208-8a38-42c5-9922-5dcb918e85c9"
                        },
                        new
                        {
                            UserId = "995ce588-b342-47b8-88f7-349365f898f9",
                            RoleId = "7023e28f-c1dc-42cd-ad76-858802f45979"
                        },
                        new
                        {
                            UserId = "cc53dc1c-a0d0-49a3-8f31-06b320fe22a9",
                            RoleId = "7023e28f-c1dc-42cd-ad76-858802f45979"
                        },
                        new
                        {
                            UserId = "4e9e311a-0926-423c-b136-eab5ba39998a",
                            RoleId = "7023e28f-c1dc-42cd-ad76-858802f45979"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("JobPortal.Models.ApplicationUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<Guid?>("CandidateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EmployerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("CandidateId");

                    b.HasIndex("EmployerId");

                    b.HasDiscriminator().HasValue("ApplicationUser");

                    b.HasData(
                        new
                        {
                            Id = "2fe7daaa-bb2f-43a6-915b-083816e43b87",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1590f093-7cdd-4bbb-82d7-678b7f96f022",
                            Email = "employer1@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "EMPLOYER1@EMAIL.COM",
                            NormalizedUserName = "EMPLOYER1@EMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAELz6kQLhTSAKnCts7uGEjpjqnUhUpR7ytmxg8kKuq83PBIywF8CPFC21xVJz1hGySQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "9b6bef18-f694-44a9-b8c0-e1817ed4e239",
                            TwoFactorEnabled = false,
                            UserName = "employer1@gmail.com",
                            EmployerId = new Guid("262ff2ba-d323-4916-b767-e9f1707ef7a2"),
                            FirstName = "Employer 1",
                            LastName = "first Employer"
                        },
                        new
                        {
                            Id = "088fffd7-94b4-448e-9b67-5619fcf19441",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a15ca4fc-6c96-4dd0-a333-7f6782c33f18",
                            Email = "employer2@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "EMPLOYER2@EMAIL.COM",
                            NormalizedUserName = "EMPLOYER2@EMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEBnKJMCz0ptskmJIabziD1T9t9dY8hYTh+DKE72+ExJpuiM+oTw3dU/T6bXM3Y6v1w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f8ab57db-3aff-4cc0-80d7-3e0bbe578bc4",
                            TwoFactorEnabled = false,
                            UserName = "employer2@gmail.com",
                            EmployerId = new Guid("680b65c6-46cf-48ac-88f7-29ab807b29d5"),
                            FirstName = "Employer 2",
                            LastName = "Second Employer"
                        },
                        new
                        {
                            Id = "06e4bc68-0d75-429c-b513-e12c2ab03494",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3ab09366-1c92-4df8-9359-fa6a607e7c05",
                            Email = "employer3@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "EMPLOYER3@EMAIL.COM",
                            NormalizedUserName = "EMPLOYER3@EMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAELMQoRAg7Iyb/fDI5q1kc0Y2gwjyMWuu4j83yTgWpAwDwE6ouIhV0TgeMVjNAFVgbw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "777741d5-4e30-42ff-a45f-d80a6a91210c",
                            TwoFactorEnabled = false,
                            UserName = "employer3@gmail.com",
                            EmployerId = new Guid("4ea1f880-57ef-4f0b-8a19-5aa356e93091"),
                            FirstName = "Employer 3",
                            LastName = "Third Employer"
                        },
                        new
                        {
                            Id = "995ce588-b342-47b8-88f7-349365f898f9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "25666956-b80e-4346-aa11-05b3ab8db405",
                            Email = "candidate1@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "CANDIDATE1@EMAIL.COM",
                            NormalizedUserName = "CANDIDATE1@EMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEHhzW/ttpWxntZczQvtVe/6wVz+M7bTVQiLv6uXkUH3fEkxfFVB1XAmTJFzQ+5jbrw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "bb100257-add6-469e-af0e-d37be33c5236",
                            TwoFactorEnabled = false,
                            UserName = "candidate@gmail.com",
                            CandidateId = new Guid("1163535c-d87f-4a75-8e85-e0d69eb9f0ea"),
                            FirstName = "Candidate 1",
                            LastName = "First CAndidate"
                        },
                        new
                        {
                            Id = "cc53dc1c-a0d0-49a3-8f31-06b320fe22a9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "51cc3bf1-de92-4ba8-bd08-a90aadca99b3",
                            Email = "candidate2@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "CANDIDATE2@EMAIL.COM",
                            NormalizedUserName = "CANDIDATE2@EMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEHWz5FWODKl87LGJrfAbZGSqJrpyHBQF4RQ7SE/tKNCudK0nxrb/KyAYsLzmEfRwbg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "135fe06c-c45c-4511-9233-1fa5caca87aa",
                            TwoFactorEnabled = false,
                            UserName = "candidate2@gmail.com",
                            CandidateId = new Guid("31bb5001-4266-4b90-992e-2a729b26d26b"),
                            FirstName = "Candidate 2",
                            LastName = "Second Candidate"
                        },
                        new
                        {
                            Id = "4e9e311a-0926-423c-b136-eab5ba39998a",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e5cbbc66-1c0b-46ff-98a2-2d5ec0f3b361",
                            Email = "candidate3@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "CANDIDATE3@EMAIL.COM",
                            NormalizedUserName = "CANDIDATE3@EMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEJrGYgsrHoCVdysboFLuM8J3iGT7DF5sj804gA1g7dUrEdMJ5zARnbkpTuM18qRVYw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "336bd7af-fd27-44c0-9695-42ce41f9da57",
                            TwoFactorEnabled = false,
                            UserName = "candidate3@gmail.com",
                            CandidateId = new Guid("6209c878-b598-4939-bccf-909e58d12504"),
                            FirstName = "Candidate 3",
                            LastName = "third Candidate"
                        });
                });

            modelBuilder.Entity("JobPortal.Models.AllJobsClasses", b =>
                {
                    b.HasOne("JobPortal.Models.JobClass", "JobClass")
                        .WithMany("AllJobsClasses")
                        .HasForeignKey("JobClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobPortal.Models.Job", "Job")
                        .WithMany("AllJobsClasses")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("JobClass");
                });

            modelBuilder.Entity("JobPortal.Models.AppliedJobs", b =>
                {
                    b.HasOne("JobPortal.Models.Candidate", "Candidate")
                        .WithMany("AppliedJobs")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobPortal.Models.Job", "Job")
                        .WithMany("AppliedJobs")
                        .HasForeignKey("JobsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("JobPortal.Models.CandidateSkills", b =>
                {
                    b.HasOne("JobPortal.Models.Candidate", "Candidate")
                        .WithMany("CandidateSkills")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobPortal.Models.Skills", "Skills")
                        .WithMany("CandidateSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");

                    b.Navigation("Skills");
                });

            modelBuilder.Entity("JobPortal.Models.Job", b =>
                {
                    b.HasOne("JobPortal.Models.Employer", "Employer")
                        .WithMany("JobOffered")
                        .HasForeignKey("EmployerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employer");
                });

            modelBuilder.Entity("JobPortal.Models.JobSkills", b =>
                {
                    b.HasOne("JobPortal.Models.Job", "Job")
                        .WithMany("JobSkills")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobPortal.Models.Skills", "Skill")
                        .WithMany("JobSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JobPortal.Models.ApplicationUser", b =>
                {
                    b.HasOne("JobPortal.Models.Candidate", "Candidate")
                        .WithMany()
                        .HasForeignKey("CandidateId");

                    b.HasOne("JobPortal.Models.Employer", "Employer")
                        .WithMany()
                        .HasForeignKey("EmployerId");

                    b.Navigation("Candidate");

                    b.Navigation("Employer");
                });

            modelBuilder.Entity("JobPortal.Models.Candidate", b =>
                {
                    b.Navigation("AppliedJobs");

                    b.Navigation("CandidateSkills");
                });

            modelBuilder.Entity("JobPortal.Models.Employer", b =>
                {
                    b.Navigation("JobOffered");
                });

            modelBuilder.Entity("JobPortal.Models.Job", b =>
                {
                    b.Navigation("AllJobsClasses");

                    b.Navigation("AppliedJobs");

                    b.Navigation("JobSkills");
                });

            modelBuilder.Entity("JobPortal.Models.JobClass", b =>
                {
                    b.Navigation("AllJobsClasses");
                });

            modelBuilder.Entity("JobPortal.Models.Skills", b =>
                {
                    b.Navigation("CandidateSkills");

                    b.Navigation("JobSkills");
                });
#pragma warning restore 612, 618
        }
    }
}
