// <auto-generated />
using System;
using JobPortal.AppDbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JobPortal.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("JobPortal.Models.AllJobsClasses", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("JobClassId")
                        .HasColumnType("int");

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JobClassId");

                    b.HasIndex("JobId");

                    b.ToTable("AllJobsClasses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            JobClassId = 1,
                            JobId = 1
                        },
                        new
                        {
                            Id = 2,
                            JobClassId = 2,
                            JobId = 1
                        },
                        new
                        {
                            Id = 3,
                            JobClassId = 3,
                            JobId = 1
                        },
                        new
                        {
                            Id = 4,
                            JobClassId = 1,
                            JobId = 2
                        },
                        new
                        {
                            Id = 5,
                            JobClassId = 2,
                            JobId = 2
                        },
                        new
                        {
                            Id = 6,
                            JobClassId = 3,
                            JobId = 3
                        });
                });

            modelBuilder.Entity("JobPortal.Models.Candidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AboutMe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("ExpectedSalary")
                        .HasColumnType("int");

                    b.Property<string>("Experience")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExperienceTime")
                        .HasColumnType("int");

                    b.Property<int>("Location")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Phone")
                        .HasColumnType("int");

                    b.Property<string>("ProfileImg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Qualification")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Candidate");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AboutMe = "Are you a User Experience Designer with a track record of delivering intuitive digital experiences that drive results? Are you a strategic storyteller and systems thinker who can concept and craft smart, world-class campaigns across a variety of mediums?\r\n\r\nDeloitte's Green Dot Agency is looking to add a Lead User Experience Designer to our experience design team. We want a passionate creative who's inspired by new trends and emerging technologies, and is able to integrate them into memorable user experiences. A problem solver who is entrepreneurial, collaborative, hungry, and humble; can deliver beautifully designed, leading-edge experiences under tight deadlines;",
                            Age = 23,
                            ExpectedSalary = 300,
                            Experience = ".Net Developer",
                            ExperienceTime = 5,
                            Location = 0,
                            Name = "Hammad Mirza",
                            Phone = 3000000,
                            ProfileImg = "https://th.bing.com/th/id/R.219c36f0da053be6810bf890683de60a?rik=TMTQOLdr87KvBA&pid=ImgRaw&r=0",
                            Qualification = 0,
                            UserId = ""
                        },
                        new
                        {
                            Id = 2,
                            AboutMe = "Are you a User Experience Designer with a track record of delivering intuitive digital experiences that drive results? Are you a strategic storyteller and systems thinker who can concept and craft smart, world-class campaigns across a variety of mediums?\r\n\r\nDeloitte's Green Dot Agency is looking to add a Lead User Experience Designer to our experience design team. We want a passionate creative who's inspired by new trends and emerging technologies, and is able to integrate them into memorable user experiences. A problem solver who is entrepreneurial, collaborative, hungry, and humble; can deliver beautifully designed, leading-edge experiences under tight deadlines;",
                            Age = 23,
                            ExpectedSalary = 400,
                            Experience = "Php Laravel",
                            ExperienceTime = 6,
                            Location = 0,
                            Name = "Ahtesham",
                            Phone = 3000000,
                            ProfileImg = "https://th.bing.com/th/id/R.219c36f0da053be6810bf890683de60a?rik=TMTQOLdr87KvBA&pid=ImgRaw&r=0",
                            Qualification = 0,
                            UserId = ""
                        },
                        new
                        {
                            Id = 3,
                            AboutMe = "Are you a User Experience Designer with a track record of delivering intuitive digital experiences that drive results? Are you a strategic storyteller and systems thinker who can concept and craft smart, world-class campaigns across a variety of mediums?\r\n\r\nDeloitte's Green Dot Agency is looking to add a Lead User Experience Designer to our experience design team. We want a passionate creative who's inspired by new trends and emerging technologies, and is able to integrate them into memorable user experiences. A problem solver who is entrepreneurial, collaborative, hungry, and humble; can deliver beautifully designed, leading-edge experiences under tight deadlines;",
                            Age = 23,
                            ExpectedSalary = 500,
                            Experience = "React Designer",
                            ExperienceTime = 8,
                            Location = 1,
                            Name = "Sohaib",
                            Phone = 3000000,
                            ProfileImg = "https://th.bing.com/th/id/R.219c36f0da053be6810bf890683de60a?rik=TMTQOLdr87KvBA&pid=ImgRaw&r=0",
                            Qualification = 1,
                            UserId = ""
                        });
                });

            modelBuilder.Entity("JobPortal.Models.CandidateSkills", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CandidateId")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.HasIndex("SkillId");

                    b.ToTable("CandidateSkills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CandidateId = 1,
                            SkillId = 4
                        },
                        new
                        {
                            Id = 2,
                            CandidateId = 1,
                            SkillId = 6
                        },
                        new
                        {
                            Id = 3,
                            CandidateId = 1,
                            SkillId = 9
                        },
                        new
                        {
                            Id = 4,
                            CandidateId = 2,
                            SkillId = 1
                        },
                        new
                        {
                            Id = 5,
                            CandidateId = 3,
                            SkillId = 3
                        },
                        new
                        {
                            Id = 6,
                            CandidateId = 3,
                            SkillId = 5
                        },
                        new
                        {
                            Id = 7,
                            CandidateId = 3,
                            SkillId = 7
                        });
                });

            modelBuilder.Entity("JobPortal.Models.Employer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CompanyAbout")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyLogo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CompanySize")
                        .HasColumnType("int");

                    b.Property<string>("CompanyWebsite")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Founded")
                        .HasColumnType("datetime2");

                    b.Property<string>("Headquarters")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employer");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyAbout = "Are you a User Experience Designer with a track record of delivering intuitive digital experiences that drive results? Are you a strategic storyteller and systems thinker who can concept and craft smart, world-class campaigns across a variety of mediums?\r\n\r\nDeloitte's Green Dot Agency is looking to add a Lead User Experience Designer to our experience design team. We want a passionate creative who's inspired by new trends and emerging technologies, and is able to integrate them into memorable user experiences. A problem solver who is entrepreneurial, collaborative, hungry, and humble; can deliver beautifully designed, leading-edge experiences under tight deadlines; and who has demonstrated proven expertise.",
                            CompanyLogo = "https://th.bing.com/th/id/R.219c36f0da053be6810bf890683de60a?rik=TMTQOLdr87KvBA&pid=ImgRaw&r=0",
                            CompanyName = "Avitex Agency",
                            CompanySize = 200,
                            CompanyWebsite = "https://jobs.nokriwp.com/",
                            Founded = new DateTime(2023, 5, 9, 12, 7, 7, 714, DateTimeKind.Utc).AddTicks(8738),
                            Headquarters = "Las Vegas, NV 89107, USA",
                            Industry = "It",
                            UserId = "2fe7daaa-bb2f-43a6-915b-083816e43b87"
                        },
                        new
                        {
                            Id = 2,
                            CompanyAbout = "Are you a User Experience Designer with a track record of delivering intuitive digital experiences that drive results? Are you a strategic storyteller and systems thinker who can concept and craft smart, world-class campaigns across a variety of mediums?\r\n\r\nDeloitte's Green Dot Agency is looking to add a Lead User Experience Designer to our experience design team. We want a passionate creative who's inspired by new trends and emerging technologies, and is able to integrate them into memorable user experiences. A problem solver who is entrepreneurial, collaborative, hungry, and humble; can deliver beautifully designed, leading-edge experiences under tight deadlines; and who has demonstrated proven expertise.",
                            CompanyLogo = "https://th.bing.com/th/id/R.219c36f0da053be6810bf890683de60a?rik=TMTQOLdr87KvBA&pid=ImgRaw&r=0",
                            CompanyName = "Demo 1",
                            CompanySize = 50,
                            CompanyWebsite = "https://jobs.nokriwp.com/",
                            Founded = new DateTime(2023, 5, 9, 12, 7, 7, 714, DateTimeKind.Utc).AddTicks(8745),
                            Headquarters = "Lahore",
                            Industry = "It",
                            UserId = "088fffd7-94b4-448e-9b67-5619fcf19441"
                        },
                        new
                        {
                            Id = 3,
                            CompanyAbout = "Are you a User Experience Designer with a track record of delivering intuitive digital experiences that drive results? Are you a strategic storyteller and systems thinker who can concept and craft smart, world-class campaigns across a variety of mediums?\r\n\r\nDeloitte's Green Dot Agency is looking to add a Lead User Experience Designer to our experience design team. We want a passionate creative who's inspired by new trends and emerging technologies, and is able to integrate them into memorable user experiences. A problem solver who is entrepreneurial, collaborative, hungry, and humble; can deliver beautifully designed, leading-edge experiences under tight deadlines; and who has demonstrated proven expertise.",
                            CompanyLogo = "https://th.bing.com/th/id/R.219c36f0da053be6810bf890683de60a?rik=TMTQOLdr87KvBA&pid=ImgRaw&r=0",
                            CompanyName = "Honda",
                            CompanySize = 600,
                            CompanyWebsite = "https://jobs.nokriwp.com/",
                            Founded = new DateTime(2023, 5, 9, 12, 7, 7, 714, DateTimeKind.Utc).AddTicks(8748),
                            Headquarters = "Islamabad",
                            Industry = "Machenical",
                            UserId = "06e4bc68-0d75-429c-b513-e12c2ab03494"
                        });
                });

            modelBuilder.Entity("JobPortal.Models.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DeadLine")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployerId")
                        .HasColumnType("int");

                    b.Property<double>("EndBudget")
                        .HasColumnType("float");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("JobExperience")
                        .HasColumnType("int");

                    b.Property<DateTime>("JobPosted")
                        .HasColumnType("datetime2");

                    b.Property<int>("JobShift")
                        .HasColumnType("int");

                    b.Property<int>("JobStatus")
                        .HasColumnType("int");

                    b.Property<int>("Location")
                        .HasColumnType("int");

                    b.Property<int>("Qualifications")
                        .HasColumnType("int");

                    b.Property<string>("Responsibility")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SalaryType")
                        .HasColumnType("int");

                    b.Property<double>("StartBudget")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("Vacancy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployerId");

                    b.ToTable("Jobs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DeadLine = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Dolor justo tempor duo ipsum accusam rebum gubergren erat. Elitr stet dolor vero clita labore gubergren. Kasd sed ipsum elitr clita rebum ut sea diam tempor. Sadipscing nonumy vero labore invidunt dolor sed, eirmod dolore amet aliquyam consetetur lorem, amet elitr clita et sed consetetur dolore accusam. Vero kasd nonumy justo rebum stet. Ipsum amet sed lorem sea magna. Rebum vero dolores dolores elitr vero dolores magna, stet sea sadipscing stet et. Est voluptua et sanctus at sanctus erat vero sed sed, amet duo no diam clita rebum duo, accusam tempor takimata clita stet nonumy rebum est invidunt stet, dolor.",
                            EmployerId = 1,
                            EndBudget = 456.0,
                            Icon = "https://img.freepik.com/premium-vector/gradient-business-investment-logo-design_269830-887.jpg?w=2000",
                            JobExperience = 1,
                            JobPosted = new DateTime(2023, 5, 9, 17, 7, 7, 624, DateTimeKind.Local).AddTicks(1735),
                            JobShift = 0,
                            JobStatus = 0,
                            Location = 0,
                            Qualifications = 0,
                            Responsibility = "Magna et elitr diam sed lorem. Diam diam stet erat no est est. Accusam sed lorem stet voluptua sit sit at stet consetetur, takimata at diam kasd gubergren elitr dolor",
                            SalaryType = 0,
                            StartBudget = 123.0,
                            Title = "Marketing Manager",
                            Type = 0,
                            Vacancy = 20
                        },
                        new
                        {
                            Id = 2,
                            DeadLine = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Dolor justo tempor duo ipsum accusam rebum gubergren erat. Elitr stet dolor vero clita labore gubergren. Kasd sed ipsum elitr clita rebum ut sea diam tempor. Sadipscing nonumy vero labore invidunt dolor sed, eirmod dolore amet aliquyam consetetur lorem, amet elitr clita et sed consetetur dolore accusam. Vero kasd nonumy justo rebum stet. Ipsum amet sed lorem sea magna. Rebum vero dolores dolores elitr vero dolores magna, stet sea sadipscing stet et. Est voluptua et sanctus at sanctus erat vero sed sed, amet duo no diam clita rebum duo, accusam tempor takimata clita stet nonumy rebum est invidunt stet, dolor.",
                            EmployerId = 1,
                            EndBudget = 777.0,
                            Icon = "https://media.istockphoto.com/id/1304359165/vector/motion-data-speed-g-letter-logo-design.jpg?s=612x612&w=0&k=20&c=2A0yYWv8zHhztdShuGoVW87yJZqseV6AKJX0QL2cVuQ=",
                            JobExperience = 6,
                            JobPosted = new DateTime(2023, 5, 9, 17, 7, 7, 624, DateTimeKind.Local).AddTicks(1755),
                            JobShift = 0,
                            JobStatus = 0,
                            Location = 2,
                            Qualifications = 0,
                            Responsibility = "Magna et elitr diam sed lorem. Diam diam stet erat no est est. Accusam sed lorem stet voluptua sit sit at stet consetetur, takimata at diam kasd gubergren elitr dolor",
                            SalaryType = 0,
                            StartBudget = 334.0,
                            Title = "Software Engineer",
                            Type = 0,
                            Vacancy = 5
                        },
                        new
                        {
                            Id = 3,
                            DeadLine = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Dolor justo tempor duo ipsum accusam rebum gubergren erat. Elitr stet dolor vero clita labore gubergren. Kasd sed ipsum elitr clita rebum ut sea diam tempor. Sadipscing nonumy vero labore invidunt dolor sed, eirmod dolore amet aliquyam consetetur lorem, amet elitr clita et sed consetetur dolore accusam. Vero kasd nonumy justo rebum stet. Ipsum amet sed lorem sea magna. Rebum vero dolores dolores elitr vero dolores magna, stet sea sadipscing stet et. Est voluptua et sanctus at sanctus erat vero sed sed, amet duo no diam clita rebum duo, accusam tempor takimata clita stet nonumy rebum est invidunt stet, dolor.",
                            EmployerId = 2,
                            EndBudget = 340.0,
                            Icon = "https://www.logodesign.net/images/abstract-logo.png",
                            JobExperience = 3,
                            JobPosted = new DateTime(2023, 5, 9, 17, 7, 7, 624, DateTimeKind.Local).AddTicks(1759),
                            JobShift = 2,
                            JobStatus = 0,
                            Location = 0,
                            Qualifications = 1,
                            Responsibility = "Magna et elitr diam sed lorem. Diam diam stet erat no est est. Accusam sed lorem stet voluptua sit sit at stet consetetur, takimata at diam kasd gubergren elitr dolor",
                            SalaryType = 0,
                            StartBudget = 190.0,
                            Title = "Product Designer",
                            Type = 5,
                            Vacancy = 50
                        });
                });

            modelBuilder.Entity("JobPortal.Models.JobClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("JobClass");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            name = "Feature"
                        },
                        new
                        {
                            Id = 2,
                            name = "Urgent"
                        },
                        new
                        {
                            Id = 3,
                            name = "Private"
                        });
                });

            modelBuilder.Entity("JobPortal.Models.JobSkills", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("SkillId");

                    b.ToTable("JobSkills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            JobId = 1,
                            SkillId = 1
                        },
                        new
                        {
                            Id = 2,
                            JobId = 1,
                            SkillId = 2
                        },
                        new
                        {
                            Id = 3,
                            JobId = 1,
                            SkillId = 3
                        },
                        new
                        {
                            Id = 4,
                            JobId = 2,
                            SkillId = 3
                        },
                        new
                        {
                            Id = 5,
                            JobId = 2,
                            SkillId = 6
                        },
                        new
                        {
                            Id = 6,
                            JobId = 3,
                            SkillId = 6
                        });
                });

            modelBuilder.Entity("JobPortal.Models.Skills", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("JobSkill")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            JobSkill = "Php"
                        },
                        new
                        {
                            Id = 2,
                            JobSkill = "JS"
                        },
                        new
                        {
                            Id = 3,
                            JobSkill = "Designing"
                        },
                        new
                        {
                            Id = 4,
                            JobSkill = "Application Development"
                        },
                        new
                        {
                            Id = 5,
                            JobSkill = "Arts"
                        },
                        new
                        {
                            Id = 6,
                            JobSkill = ".Net"
                        },
                        new
                        {
                            Id = 7,
                            JobSkill = "Development"
                        },
                        new
                        {
                            Id = 8,
                            JobSkill = "Modeling"
                        },
                        new
                        {
                            Id = 9,
                            JobSkill = "Architecture"
                        },
                        new
                        {
                            Id = 10,
                            JobSkill = "Management"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1d8bbcb9-6d72-4776-b97a-54dd330775ca",
                            ConcurrencyStamp = "cd7d5c65-7d6b-49e2-8b3f-b69ab4a5263c",
                            Name = "admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "7023e28f-c1dc-42cd-ad76-858802f45979",
                            ConcurrencyStamp = "c3963357-100a-4d87-9191-c51d3ee91c2c",
                            Name = "candidate",
                            NormalizedName = "CANDIDATE"
                        },
                        new
                        {
                            Id = "b189a208-8a38-42c5-9922-5dcb918e85c9",
                            ConcurrencyStamp = "8f74bb4f-3374-4f7a-bd1b-562a2a40d547",
                            Name = "employer",
                            NormalizedName = "EMPLOYER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "2fe7daaa-bb2f-43a6-915b-083816e43b87",
                            RoleId = "b189a208-8a38-42c5-9922-5dcb918e85c9"
                        },
                        new
                        {
                            UserId = "088fffd7-94b4-448e-9b67-5619fcf19441",
                            RoleId = "b189a208-8a38-42c5-9922-5dcb918e85c9"
                        },
                        new
                        {
                            UserId = "06e4bc68-0d75-429c-b513-e12c2ab03494",
                            RoleId = "b189a208-8a38-42c5-9922-5dcb918e85c9"
                        },
                        new
                        {
                            UserId = "995ce588-b342-47b8-88f7-349365f898f9",
                            RoleId = "7023e28f-c1dc-42cd-ad76-858802f45979"
                        },
                        new
                        {
                            UserId = "cc53dc1c-a0d0-49a3-8f31-06b320fe22a9",
                            RoleId = "7023e28f-c1dc-42cd-ad76-858802f45979"
                        },
                        new
                        {
                            UserId = "4e9e311a-0926-423c-b136-eab5ba39998a",
                            RoleId = "7023e28f-c1dc-42cd-ad76-858802f45979"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("JobPortal.Models.ApplicationUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<int?>("EmployeerId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("EmployeerId");

                    b.HasDiscriminator().HasValue("ApplicationUser");

                    b.HasData(
                        new
                        {
                            Id = "2fe7daaa-bb2f-43a6-915b-083816e43b87",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b88bdf56-e89a-4d49-a6a1-17899a054454",
                            Email = "employer1@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "EMPLOYER1@EMAIL.COM",
                            NormalizedUserName = "EMPLOYER1@EMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEFqrzcrHD3YKEKHkfoBHTInXEnzgAf6Y4ozlMcYb0inXDPx/CYdinH/WJSccY2KJug==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "64f4cf18-4bb9-419b-8cd9-58996aecb57a",
                            TwoFactorEnabled = false,
                            UserName = "employer1@gmail.com",
                            EmployeerId = 1,
                            FirstName = "Employer 1",
                            LastName = "first Employer"
                        },
                        new
                        {
                            Id = "088fffd7-94b4-448e-9b67-5619fcf19441",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "007b9eb2-4275-4294-a6b2-13df4ee5ae8a",
                            Email = "employer2@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "EMPLOYER2@EMAIL.COM",
                            NormalizedUserName = "EMPLOYER2@EMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEBjZNIvTw8+RlRmqU8iCCaRNFoM80JZPy8jyIHyxemNVnq0Zd6l3S6M1toizoHuWdw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e2314102-d471-49d2-98a0-16fa6797b22f",
                            TwoFactorEnabled = false,
                            UserName = "employer2@gmail.com",
                            EmployeerId = 2,
                            FirstName = "Employer 2",
                            LastName = "Second Employer"
                        },
                        new
                        {
                            Id = "06e4bc68-0d75-429c-b513-e12c2ab03494",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "571541e9-f03b-45c5-89cb-5a6de064e42a",
                            Email = "employer3@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "EMPLOYER3@EMAIL.COM",
                            NormalizedUserName = "EMPLOYER3@EMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEGbEdzoDEtaHV2sjMjcE1zqHL81dQMgkH7CqdHNgAJl410Vgf14ViqnDPbIBNcICyQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e5b4ef44-1f3f-4053-8eb4-776dad094115",
                            TwoFactorEnabled = false,
                            UserName = "employer3@gmail.com",
                            EmployeerId = 3,
                            FirstName = "Employer 3",
                            LastName = "Third Employer"
                        },
                        new
                        {
                            Id = "995ce588-b342-47b8-88f7-349365f898f9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1043d906-133d-4d75-9b83-39b8d3baf469",
                            Email = "candidate1@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "CANDIDATE1@EMAIL.COM",
                            NormalizedUserName = "CANDIDATE1@EMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEGQpe4DNj8E1rmFR2pi7K214+ed6VJNcvB8HAbIl7x3ffN7TiVCvuaDxpnQYt1c8SA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "7f1883d3-2e57-4cd3-ab61-913c8735f9d7",
                            TwoFactorEnabled = false,
                            UserName = "candidate@gmail.com",
                            FirstName = "Candidate 1",
                            LastName = "First CAndidate"
                        },
                        new
                        {
                            Id = "cc53dc1c-a0d0-49a3-8f31-06b320fe22a9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "bfb8c3ef-42d7-4b75-8ea2-ae2cf9293f3e",
                            Email = "candidate2@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "CANDIDATE2@EMAIL.COM",
                            NormalizedUserName = "CANDIDATE2@EMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEIPPVWxzUI2deunQo4h7k5d+OAVlwI/Bvv2PqerJoOi2LaDZ+N3/Rla6dSwzFQnPsw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "65a49954-8ac8-4e87-b030-cdb826c2583b",
                            TwoFactorEnabled = false,
                            UserName = "candidate2@gmail.com",
                            FirstName = "Candidate 2",
                            LastName = "Second Candidate"
                        },
                        new
                        {
                            Id = "4e9e311a-0926-423c-b136-eab5ba39998a",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f2d1cd47-f120-4358-a245-19c06480c5be",
                            Email = "candidate3@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "CANDIDATE3@EMAIL.COM",
                            NormalizedUserName = "CANDIDATE3@EMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEImlsxyzzki4HXgOPffKdjemt4i4PagUv8SaLOXT1akgFt6biK6Gt1A2m7cmh5WbOw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "449bd3b7-f60a-464a-83ba-9f90698bbc1a",
                            TwoFactorEnabled = false,
                            UserName = "candidate3@gmail.com",
                            FirstName = "Candidate 3",
                            LastName = "third Candidate"
                        });
                });

            modelBuilder.Entity("JobPortal.Models.AllJobsClasses", b =>
                {
                    b.HasOne("JobPortal.Models.JobClass", "JobClass")
                        .WithMany("AllJobsClasses")
                        .HasForeignKey("JobClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobPortal.Models.Job", "Job")
                        .WithMany("AllJobsClasses")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("JobClass");
                });

            modelBuilder.Entity("JobPortal.Models.CandidateSkills", b =>
                {
                    b.HasOne("JobPortal.Models.Candidate", "Candidate")
                        .WithMany("CandidateSkills")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobPortal.Models.Skills", "Skills")
                        .WithMany("CandidateSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");

                    b.Navigation("Skills");
                });

            modelBuilder.Entity("JobPortal.Models.Job", b =>
                {
                    b.HasOne("JobPortal.Models.Employer", "Employer")
                        .WithMany("JobOffered")
                        .HasForeignKey("EmployerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employer");
                });

            modelBuilder.Entity("JobPortal.Models.JobSkills", b =>
                {
                    b.HasOne("JobPortal.Models.Job", "Job")
                        .WithMany("JobSkills")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobPortal.Models.Skills", "Skill")
                        .WithMany("JobSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JobPortal.Models.ApplicationUser", b =>
                {
                    b.HasOne("JobPortal.Models.Employer", "Employeer")
                        .WithMany()
                        .HasForeignKey("EmployeerId");

                    b.Navigation("Employeer");
                });

            modelBuilder.Entity("JobPortal.Models.Candidate", b =>
                {
                    b.Navigation("CandidateSkills");
                });

            modelBuilder.Entity("JobPortal.Models.Employer", b =>
                {
                    b.Navigation("JobOffered");
                });

            modelBuilder.Entity("JobPortal.Models.Job", b =>
                {
                    b.Navigation("AllJobsClasses");

                    b.Navigation("JobSkills");
                });

            modelBuilder.Entity("JobPortal.Models.JobClass", b =>
                {
                    b.Navigation("AllJobsClasses");
                });

            modelBuilder.Entity("JobPortal.Models.Skills", b =>
                {
                    b.Navigation("CandidateSkills");

                    b.Navigation("JobSkills");
                });
#pragma warning restore 612, 618
        }
    }
}
